// Codegen: packages/levels/catalog/uci.yaml -> packages/core/src/messages/generated.ts
//
// Emits a TS union per enum, an interface per complex type / message (near-flat),
// and a runtime MESSAGE_CATALOG metadata object (enums, envelope, messages, types
// with citations) consumed by the sim, inspector, and validator.
//
// Output is committed; run `npm run gen:catalog` to regenerate after editing the YAML.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CatalogComplexType, CatalogField } from "./catalog-source.ts";
import { loadCatalog, REPO_ROOT } from "./catalog-source.ts";

const OUT = resolve(REPO_ROOT, "packages/core/src/messages/generated.ts");

function fieldType(f: CatalogField): string {
  if (f.enum) return f.enum;
  if (f.ref) return f.ref;
  return "string";
}

function emitInterface(t: CatalogComplexType): string {
  const lines = [`export interface ${t.name} {`];
  for (const f of t.fields) lines.push(`  ${f.name}${f.required ? "" : "?"}: ${fieldType(f)};`);
  lines.push("}");
  return lines.join("\n");
}

function main(): void {
  const cat = loadCatalog();

  const enumTypes = cat.enums
    .map(
      (e) =>
        `export type ${e.name} =\n  | ${e.values.map((v) => JSON.stringify(v)).join("\n  | ")};`,
    )
    .join("\n\n");

  const interfaces = [...cat.envelope, ...cat.types, ...cat.messages]
    .map(emitInterface)
    .join("\n\n");

  const meta = {
    version: cat.version,
    enums: Object.fromEntries(cat.enums.map((e) => [e.name, e])),
    envelope: Object.fromEntries(cat.envelope.map((t) => [t.name, t])),
    messages: Object.fromEntries(cat.messages.map((m) => [m.name, m])),
    types: Object.fromEntries(cat.types.map((t) => [t.name, t])),
  };

  const body = `// AUTO-GENERATED by tools/gen-catalog.ts from packages/levels/catalog/uci.yaml.
// Do not edit by hand; run \`npm run gen:catalog\`.

/* --- Enum unions --- */
${enumTypes}

/* --- Message & type interfaces --- */
${interfaces}

/* --- Runtime catalog metadata (citations, field trees) --- */
export const MESSAGE_CATALOG = ${JSON.stringify(meta, null, 2)} as const;

export type MessageCatalog = typeof MESSAGE_CATALOG;
`;

  writeFileSync(OUT, body);
  process.stderr.write(`gen-catalog: wrote ${OUT}\n`);
}

main();
