// AUTO-GENERATED by tools/gen-catalog.ts — DO NOT EDIT BY HAND.
// Source: packages/levels/catalog/tier1.yaml. Regenerate with `npm run gen:catalog`.
// Every name here is policed against the A-GRA XSD by tools/check-fidelity.ts.

export interface MA_FlightCapabilityMT {
  CapabilityID: string;
  CapabilityType: "HSA_CSA";
  MinAltitude?: number;
  MaxAltitude?: number;
  MinAirspeed?: number;
  MaxAirspeed?: number;
}

export interface MA_FlightCapabilityStatusMT {
  CapabilityID: string;
  Availability: "AVAILABLE" | "UNAVAILABLE" | "TEMPORARILY_UNAVAILABLE";
}

export interface MA_ControlRequestMT {
  RequestType: "ACQUIRE" | "RELEASE";
  CapabilityID: string;
}

export interface MA_ControlRequestStatusMT {
  CapabilityID: string;
  ApprovalRequestProcessingState: "APPROVED" | "PENDING" | "REJECTED" | "CANCELED";
}

export interface ControlStatusMT {
  CapabilityID: string;
  PrimaryController?: string;
  SecondaryController?: string;
}

export interface MA_FlightCommandMT {
  CommandID: string;
  CommandState: "NEW" | "UPDATE" | "CANCEL";
  CapabilityID: string;
  Altitude?: number;
  Speed?: number;
  Heading?: number;
  Course?: number;
}

export interface MA_FlightCommandStatusMT {
  CommandID: string;
  CommandProcessingState: "RECEIVED" | "ACCEPTED" | "REJECTED" | "CANCELED";
  ValidationResult?: "FLIGHT_COMMAND_VALID" | "PERFORMANCE_LIMIT_EXCEEDED" | "CAPABILITY_NOT_SUPPORTED" | "VIOLATION_ENDURANCE" | "VIOLATION_GEOFENCE" | "VIOLATION_AIR_TRAFFIC" | "VIOLATION_TERRAIN" | "INVALID_WAYPOINT" | "INVALID_CURVE";
}

export interface MA_FlightActivityMT {
  ActivityID: string;
  Altitude?: number;
  Heading?: number;
  Speed?: number;
}

export interface MA_PositionReportDetailedMT {
  Latitude?: number;
  Longitude?: number;
  Altitude?: number;
  NavigationSolutionState?: "ALIGNING" | "FREE_INERTIAL" | "GPS" | "BLENDED";
}

export interface NavigationReportMT {
  Fuel?: number;
  Percent?: number;
}

/** Maps each message type name to its pruned payload interface. */
export interface MessagePayloads {
  MA_FlightCapabilityMT: MA_FlightCapabilityMT;
  MA_FlightCapabilityStatusMT: MA_FlightCapabilityStatusMT;
  MA_ControlRequestMT: MA_ControlRequestMT;
  MA_ControlRequestStatusMT: MA_ControlRequestStatusMT;
  ControlStatusMT: ControlStatusMT;
  MA_FlightCommandMT: MA_FlightCommandMT;
  MA_FlightCommandStatusMT: MA_FlightCommandStatusMT;
  MA_FlightActivityMT: MA_FlightActivityMT;
  MA_PositionReportDetailedMT: MA_PositionReportDetailedMT;
  NavigationReportMT: NavigationReportMT;
}

/** Union of all Tier-1 message type names. */
export type MessageTypeName = keyof MessagePayloads;

export type FieldType = "string" | "number" | "boolean" | "enum" | "object";
export type Direction = "MA->FA" | "FA->MA";

export interface CatalogFieldMeta {
  readonly name: string;
  readonly path: string;
  readonly type: FieldType;
  readonly values?: readonly string[];
  readonly required: boolean;
}

export interface CatalogMessageMeta {
  readonly name: MessageTypeName;
  readonly tier: number;
  readonly direction: Direction;
  readonly citation: string;
  readonly summary: string;
  readonly fields: readonly CatalogFieldMeta[];
}

/** Runtime metadata for every Tier-1 message, keyed by type name. */
export const MESSAGE_CATALOG = {
  "MA_FlightCapabilityMT": {
    "name": "MA_FlightCapabilityMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.2.4 Control Mode Authorization",
    "summary": "FA advertises a commandable flight capability and its per-mode performance envelope. The envelope FA advertises here is exactly what its validator enforces later — the pedagogical contract (docs/04).",
    "fields": [
      {
        "name": "CapabilityID",
        "path": "MessageData.Capability.CapabilityID",
        "type": "string",
        "required": true
      },
      {
        "name": "CapabilityType",
        "path": "MessageData.Capability.CapabilityType",
        "type": "enum",
        "values": [
          "HSA_CSA"
        ],
        "required": true
      },
      {
        "name": "MinAltitude",
        "path": "MessageData.Capability.FlightCapabilityPerformanceProfile.HSA_CSA_PerformanceProfile.MinAltitude",
        "type": "number",
        "required": false
      },
      {
        "name": "MaxAltitude",
        "path": "MessageData.Capability.FlightCapabilityPerformanceProfile.HSA_CSA_PerformanceProfile.MaxAltitude",
        "type": "number",
        "required": false
      },
      {
        "name": "MinAirspeed",
        "path": "MessageData.Capability.FlightCapabilityPerformanceProfile.HSA_CSA_PerformanceProfile.MinAirspeed",
        "type": "number",
        "required": false
      },
      {
        "name": "MaxAirspeed",
        "path": "MessageData.Capability.FlightCapabilityPerformanceProfile.HSA_CSA_PerformanceProfile.MaxAirspeed",
        "type": "number",
        "required": false
      }
    ]
  },
  "MA_FlightCapabilityStatusMT": {
    "name": "MA_FlightCapabilityStatusMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.2.4 Control Mode Authorization (readiness)",
    "summary": "FA signals whether an advertised capability is ready to be controlled.",
    "fields": [
      {
        "name": "CapabilityID",
        "path": "MessageData.CapabilityStatus.CapabilityID",
        "type": "string",
        "required": true
      },
      {
        "name": "Availability",
        "path": "MessageData.CapabilityStatus.AvailabilityInfo.Availability",
        "type": "enum",
        "values": [
          "AVAILABLE",
          "UNAVAILABLE",
          "TEMPORARILY_UNAVAILABLE"
        ],
        "required": true
      }
    ]
  },
  "MA_ControlRequestMT": {
    "name": "MA_ControlRequestMT",
    "tier": 1,
    "direction": "MA->FA",
    "citation": "VI Vol §1.2.2.7 Receive Control Request",
    "summary": "MA requests control of a capability. The game correlates the request to a capability by CapabilityID (fidelity lie #4: the real assignment links via Controllee/ControlType; correlation semantics preserved, format shortened).",
    "fields": [
      {
        "name": "RequestType",
        "path": "MessageData.RequestType",
        "type": "enum",
        "values": [
          "ACQUIRE",
          "RELEASE"
        ],
        "required": true
      },
      {
        "name": "CapabilityID",
        "path": "MessageData.ControlAssignment.CapabilityID",
        "type": "string",
        "required": true
      }
    ]
  },
  "MA_ControlRequestStatusMT": {
    "name": "MA_ControlRequestStatusMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.2.7 Receive Control Request (status)",
    "summary": "FA approves, defers (PENDING), or rejects a control request.",
    "fields": [
      {
        "name": "CapabilityID",
        "path": "MessageData.ControlAssignment.CapabilityID",
        "type": "string",
        "required": true
      },
      {
        "name": "ApprovalRequestProcessingState",
        "path": "MessageData.ApprovalRequestProcessingState",
        "type": "enum",
        "values": [
          "APPROVED",
          "PENDING",
          "REJECTED",
          "CANCELED"
        ],
        "required": true
      }
    ]
  },
  "ControlStatusMT": {
    "name": "ControlStatusMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.6.2 Publish Control Status",
    "summary": "Who FA is listening to per capability. FA is always PrimaryController; MA is at most SecondaryController. Commands are honored only while MA appears as the SecondaryController for that capability (fidelity lie #8).",
    "fields": [
      {
        "name": "CapabilityID",
        "path": "MessageData.ControlType.CapabilityControl.CapabilityID",
        "type": "string",
        "required": true
      },
      {
        "name": "PrimaryController",
        "path": "MessageData.ControlType.CapabilityControl.PrimaryController",
        "type": "string",
        "required": false
      },
      {
        "name": "SecondaryController",
        "path": "MessageData.ControlType.CapabilityControl.SecondaryController.SystemID",
        "type": "string",
        "required": false
      }
    ]
  },
  "MA_FlightCommandMT": {
    "name": "MA_FlightCommandMT",
    "tier": 1,
    "direction": "MA->FA",
    "citation": "VI Vol §1.2.2.2 Control by HSA/CSA Command",
    "summary": "Persistent HSA/CSA flight vector command. HSA has no completion state — the brain infers arrival from position reports (the 1.2 lesson).",
    "fields": [
      {
        "name": "CommandID",
        "path": "MessageData.Command.Capability.CommandID",
        "type": "string",
        "required": true
      },
      {
        "name": "CommandState",
        "path": "MessageData.Command.Capability.CommandState",
        "type": "enum",
        "values": [
          "NEW",
          "UPDATE",
          "CANCEL"
        ],
        "required": true
      },
      {
        "name": "CapabilityID",
        "path": "MessageData.Command.Capability.CapabilityID",
        "type": "string",
        "required": true
      },
      {
        "name": "Altitude",
        "path": "MessageData.Command.Capability.FlightControlMode.HSA_CSA.Altitude",
        "type": "number",
        "required": false
      },
      {
        "name": "Speed",
        "path": "MessageData.Command.Capability.FlightControlMode.HSA_CSA.Speed",
        "type": "number",
        "required": false
      },
      {
        "name": "Heading",
        "path": "MessageData.Command.Capability.FlightControlMode.HSA_CSA.Direction.Heading",
        "type": "number",
        "required": false
      },
      {
        "name": "Course",
        "path": "MessageData.Command.Capability.FlightControlMode.HSA_CSA.Direction.Course",
        "type": "number",
        "required": false
      }
    ]
  },
  "MA_FlightCommandStatusMT": {
    "name": "MA_FlightCommandStatusMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.2.2 Control by HSA/CSA Command (status)",
    "summary": "FA accepts or rejects a flight command; rejection carries a ValidationResult reason.",
    "fields": [
      {
        "name": "CommandID",
        "path": "MessageData.CommandID",
        "type": "string",
        "required": true
      },
      {
        "name": "CommandProcessingState",
        "path": "MessageData.CommandProcessingState",
        "type": "enum",
        "values": [
          "RECEIVED",
          "ACCEPTED",
          "REJECTED",
          "CANCELED"
        ],
        "required": true
      },
      {
        "name": "ValidationResult",
        "path": "MessageData.CannotComplyDetails.ValidationResult",
        "type": "enum",
        "values": [
          "FLIGHT_COMMAND_VALID",
          "PERFORMANCE_LIMIT_EXCEEDED",
          "CAPABILITY_NOT_SUPPORTED",
          "VIOLATION_ENDURANCE",
          "VIOLATION_GEOFENCE",
          "VIOLATION_AIR_TRAFFIC",
          "VIOLATION_TERRAIN",
          "INVALID_WAYPOINT",
          "INVALID_CURVE"
        ],
        "required": false
      }
    ]
  },
  "MA_FlightActivityMT": {
    "name": "MA_FlightActivityMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.6.8 Receive Vehicle State Data (activity)",
    "summary": "FA reports the active flight activity resulting from an accepted command.",
    "fields": [
      {
        "name": "ActivityID",
        "path": "MessageData.Activity.ActivityID",
        "type": "string",
        "required": true
      },
      {
        "name": "Altitude",
        "path": "MessageData.Activity.VehicleCommandState.Altitude",
        "type": "number",
        "required": false
      },
      {
        "name": "Heading",
        "path": "MessageData.Activity.VehicleCommandState.Heading",
        "type": "number",
        "required": false
      },
      {
        "name": "Speed",
        "path": "MessageData.Activity.VehicleCommandState.Speed",
        "type": "number",
        "required": false
      }
    ]
  },
  "MA_PositionReportDetailedMT": {
    "name": "MA_PositionReportDetailedMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.6.8 Receive Vehicle State Data (position)",
    "summary": "Periodic ownship state. The brain consumes this to know where it is and whether it has arrived (win conditions are world-state, never message-sent).",
    "fields": [
      {
        "name": "Latitude",
        "path": "MessageData.PositionReportData.Kinematics.Position.Latitude",
        "type": "number",
        "required": false
      },
      {
        "name": "Longitude",
        "path": "MessageData.PositionReportData.Kinematics.Position.Longitude",
        "type": "number",
        "required": false
      },
      {
        "name": "Altitude",
        "path": "MessageData.PositionReportData.Kinematics.Position.Altitude",
        "type": "number",
        "required": false
      },
      {
        "name": "NavigationSolutionState",
        "path": "MessageData.PositionReportData.NavigationSolutionState",
        "type": "enum",
        "values": [
          "ALIGNING",
          "FREE_INERTIAL",
          "GPS",
          "BLENDED"
        ],
        "required": false
      }
    ]
  },
  "NavigationReportMT": {
    "name": "NavigationReportMT",
    "tier": 1,
    "direction": "FA->MA",
    "citation": "VI Vol §1.2.6.8 Receive Vehicle State Data (endurance)",
    "summary": "Periodic ownship endurance. FA publishes remaining fuel (mass, kg) and percent of capacity; the brain reads it to fly a sustainable profile (the Bingo lesson). Real Endurance carries Fuel/Duration/DurationEnd/Percent — pruned here to flat Fuel + Percent (fidelity lie #5).",
    "fields": [
      {
        "name": "Fuel",
        "path": "MessageData.Endurance.Fuel",
        "type": "number",
        "required": false
      },
      {
        "name": "Percent",
        "path": "MessageData.Endurance.Percent",
        "type": "number",
        "required": false
      }
    ]
  }
} as const satisfies Record<MessageTypeName, CatalogMessageMeta>;

/** All Tier-1 message type names, in catalog order. */
export const MESSAGE_TYPE_NAMES = ["MA_FlightCapabilityMT","MA_FlightCapabilityStatusMT","MA_ControlRequestMT","MA_ControlRequestStatusMT","ControlStatusMT","MA_FlightCommandMT","MA_FlightCommandStatusMT","MA_FlightActivityMT","MA_PositionReportDetailedMT","NavigationReportMT"] as const satisfies readonly MessageTypeName[];
