// Codegen: packages/levels/catalog/tier1.yaml -> packages/core/src/messages/generated.ts
//
// Emits a TS interface per message (pruned, near-flat payload shape) plus a runtime
// MESSAGE_CATALOG metadata map (field names/paths/types/enums, citations) used by the
// sim, and later by send-forms, the inspector, and required-field validation.
//
// Output is committed; run `npm run gen:catalog` to regenerate after editing the YAML.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CatalogField, CatalogMessage } from "./catalog-source.ts";
import { loadCatalog, REPO_ROOT } from "./catalog-source.ts";

const OUT = resolve(REPO_ROOT, "packages/core/src/messages/generated.ts");

function tsType(field: CatalogField): string {
  switch (field.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "enum":
      return (field.values ?? []).map((v) => JSON.stringify(v)).join(" | ") || "string";
    case "object":
      return "Record<string, unknown>";
  }
}

function emitInterface(msg: CatalogMessage): string {
  const lines = [`export interface ${msg.name} {`];
  for (const f of msg.fields) {
    const opt = f.required ? "" : "?";
    lines.push(`  ${f.name}${opt}: ${tsType(f)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function main(): void {
  const catalog = loadCatalog();
  const names = catalog.messages.map((m) => m.name);

  const catalogObject: Record<string, unknown> = {};
  for (const m of catalog.messages) {
    catalogObject[m.name] = {
      name: m.name,
      tier: m.tier,
      direction: m.direction,
      citation: m.citation,
      summary: m.summary,
      fields: m.fields.map((f) => ({
        name: f.name,
        path: f.path,
        type: f.type,
        ...(f.values ? { values: f.values } : {}),
        required: f.required,
      })),
    };
  }

  const out = `// AUTO-GENERATED by tools/gen-catalog.ts — DO NOT EDIT BY HAND.
// Source: packages/levels/catalog/tier1.yaml + tier2-ms.yaml. Regenerate with \`npm run gen:catalog\`.
// Every name here is policed against the A-GRA XSD by tools/check-fidelity.ts.

${catalog.messages.map(emitInterface).join("\n\n")}

/** Maps each message type name to its pruned payload interface. */
export interface MessagePayloads {
${names.map((n) => `  ${n}: ${n};`).join("\n")}
}

/** Union of all Tier-1 message type names. */
export type MessageTypeName = keyof MessagePayloads;

export type FieldType = "string" | "number" | "boolean" | "enum" | "object";
export type Direction = "MA->FA" | "FA->MA" | "MA->MS" | "MS->MA";

export interface CatalogFieldMeta {
  readonly name: string;
  readonly path: string;
  readonly type: FieldType;
  readonly values?: readonly string[];
  readonly required: boolean;
}

export interface CatalogMessageMeta {
  readonly name: MessageTypeName;
  readonly tier: number;
  readonly direction: Direction;
  readonly citation: string;
  readonly summary: string;
  readonly fields: readonly CatalogFieldMeta[];
}

/** Runtime metadata for every Tier-1 message, keyed by type name. */
export const MESSAGE_CATALOG = ${JSON.stringify(catalogObject, null, 2)} as const satisfies Record<MessageTypeName, CatalogMessageMeta>;

/** All Tier-1 message type names, in catalog order. */
export const MESSAGE_TYPE_NAMES = ${JSON.stringify(names)} as const satisfies readonly MessageTypeName[];
`;

  writeFileSync(OUT, out, "utf8");
  process.stderr.write(`gen-catalog: wrote ${catalog.messages.length} messages -> ${OUT}\n`);
}

main();
