// AUTO-GENERATED by tools/gen-catalog.ts from packages/levels/catalog/uci.yaml.
// Do not edit by hand; run `npm run gen:catalog`.

/* --- Enum unions --- */
export type CommandStateEnum =
  | "NEW"
  | "UPDATE"
  | "CANCEL";

export type CommandProcessingStateEnum =
  | "RECEIVED"
  | "ACCEPTED"
  | "REJECTED"
  | "CANCELED";

export type MessageModeEnum =
  | "LIVE"
  | "EXERCISE"
  | "SIMULATION"
  | "NONEXERCISE_SIMULATION";

/* --- Message & type interfaces --- */
export interface MessageType {
  SecurityInformation: string;
  MessageHeader: HeaderType;
}

export interface HeaderType {
  SystemID: string;
  Timestamp: string;
  SchemaVersion: string;
  Mode?: MessageModeEnum;
  ServiceID?: string;
  MissionID?: string;
}

export interface ID_Type {
  UUID: string;
  DescriptiveLabel?: string;
}

export interface TaskCommand {
  CommandID: ID_Type;
  CommandState: CommandStateEnum;
}

export interface TaskCommandStatus {
  CommandID: ID_Type;
  CommandProcessingState: CommandProcessingStateEnum;
}

/* --- Runtime catalog metadata (citations, field trees) --- */
export const MESSAGE_CATALOG = {
  "version": 1,
  "enums": {
    "CommandStateEnum": {
      "name": "CommandStateEnum",
      "values": [
        "NEW",
        "UPDATE",
        "CANCEL"
      ],
      "cite": "SPC-001 §5.1.1 (CommandBaseType); XSD CommandStateEnum"
    },
    "CommandProcessingStateEnum": {
      "name": "CommandProcessingStateEnum",
      "values": [
        "RECEIVED",
        "ACCEPTED",
        "REJECTED",
        "CANCELED"
      ],
      "cite": "SPC-001 §5.1.1 Fig 5.1-3, Table 5.1-2; RECEIVED may not be reported; ACCEPTED/REJECTED/CANCELED terminal"
    },
    "MessageModeEnum": {
      "name": "MessageModeEnum",
      "values": [
        "LIVE",
        "EXERCISE",
        "SIMULATION",
        "NONEXERCISE_SIMULATION"
      ],
      "cite": "XSD MessageModeEnum"
    }
  },
  "envelope": {
    "MessageType": {
      "name": "MessageType",
      "cite": "XSD MessageType — abstract envelope",
      "fields": [
        {
          "name": "SecurityInformation",
          "required": true,
          "cite": "read-only marking chip; type in UCI_SecurityMarkings (not vendored)"
        },
        {
          "name": "MessageHeader",
          "required": true,
          "ref": "HeaderType"
        }
      ]
    },
    "HeaderType": {
      "name": "HeaderType",
      "cite": "XSD HeaderType",
      "fields": [
        {
          "name": "SystemID",
          "required": true,
          "cite": "player-filled (beat 1); missing SystemID => ENV HeaderType finding"
        },
        {
          "name": "Timestamp",
          "required": true,
          "cite": "XSD HeaderType (DateTimeType)"
        },
        {
          "name": "SchemaVersion",
          "required": true,
          "cite": "XSD HeaderType (UCI_SchemaVersionStringType)"
        },
        {
          "name": "Mode",
          "required": false,
          "enum": "MessageModeEnum"
        },
        {
          "name": "ServiceID",
          "required": false,
          "cite": "optional; omitted from the 4-field inspector"
        },
        {
          "name": "MissionID",
          "required": false,
          "cite": "optional; omitted from the 4-field inspector"
        }
      ]
    }
  },
  "messages": {
    "TaskCommand": {
      "name": "TaskCommand",
      "cite": "UNIS §4.6 CERT UNIS-000105; SPC-001 §5.1.1 CERT SCH-002461; XSD TaskCommand / TaskCommandMT",
      "fields": [
        {
          "name": "CommandID",
          "required": true,
          "ref": "ID_Type",
          "cite": "ID_Type.UUID; RQMT USTD-000436 (Leach-Salz/nil), RQMT USTD-000673 (canonical string)"
        },
        {
          "name": "CommandState",
          "required": true,
          "enum": "CommandStateEnum"
        }
      ],
      "mt": "TaskCommandMT",
      "role": "request"
    },
    "TaskCommandStatus": {
      "name": "TaskCommandStatus",
      "cite": "UNIS §4.6 CERT UNIS-000105; SPC-001 §5.1.1 CERT SCH-002461; XSD TaskCommandStatus / TaskCommandStatusMT",
      "fields": [
        {
          "name": "CommandID",
          "required": true,
          "ref": "ID_Type",
          "cite": "correlation key back to the TaskCommand"
        },
        {
          "name": "CommandProcessingState",
          "required": true,
          "enum": "CommandProcessingStateEnum"
        }
      ],
      "mt": "TaskCommandStatusMT",
      "role": "response"
    }
  },
  "types": {
    "ID_Type": {
      "name": "ID_Type",
      "cite": "XSD ID_Type = UUID + optional DescriptiveLabel",
      "fields": [
        {
          "name": "UUID",
          "required": true
        },
        {
          "name": "DescriptiveLabel",
          "required": false
        }
      ]
    }
  }
} as const;

export type MessageCatalog = typeof MESSAGE_CATALOG;
