// AUTO-GENERATED by tools/gen-catalog.ts from packages/levels/catalog/uci.yaml.
// Do not edit by hand; run `npm run gen:catalog`.

/* --- Enum unions --- */
export type CommandStateEnum =
  | "NEW"
  | "UPDATE"
  | "CANCEL";

export type CommandProcessingStateEnum =
  | "RECEIVED"
  | "ACCEPTED"
  | "REJECTED"
  | "CANCELED";

export type MessageModeEnum =
  | "LIVE"
  | "EXERCISE"
  | "SIMULATION"
  | "NONEXERCISE_SIMULATION";

export type CannotComplyEnum =
  | "INVALID_INPUT_PARAMETER";

export type RequestProcessingStateEnum =
  | "QUEUED"
  | "PROCESSING"
  | "COMPLETED"
  | "FAILED"
  | "CANCELED"
  | "REJECTED";

/* --- Message & type interfaces --- */
export interface MessageType {
  SecurityInformation: string;
  MessageHeader: HeaderType;
}

export interface HeaderType {
  SystemID: string;
  Timestamp: string;
  SchemaVersion: string;
  Mode?: MessageModeEnum;
  ServiceID?: string;
  MissionID?: string;
}

export interface ID_Type {
  UUID: string;
  DescriptiveLabel?: string;
}

export interface TaskCommand {
  CommandID: ID_Type;
  CommandState: CommandStateEnum;
}

export interface TaskCommandStatus {
  CommandID: ID_Type;
  CommandProcessingState: CommandProcessingStateEnum;
  CommandProcessingStateReason?: string;
}

export interface SubsystemStatus {
}

export interface Entity {
}

export interface SubsystemStatusDataRequest {
}

export interface SubsystemStatusDataRequestStatus {
  RequestProcessingState: RequestProcessingStateEnum;
}

export interface AnalysisRouteRequest {
}

export interface AnalysisRouteRequestStatus {
  RequestProcessingState: RequestProcessingStateEnum;
}

/* --- Runtime catalog metadata (citations, field trees) --- */
export const MESSAGE_CATALOG = {
  "version": 1,
  "enums": {
    "CommandStateEnum": {
      "name": "CommandStateEnum",
      "values": [
        "NEW",
        "UPDATE",
        "CANCEL"
      ],
      "cite": "SPC-001 §5.1.1 (CommandBaseType); XSD CommandStateEnum"
    },
    "CommandProcessingStateEnum": {
      "name": "CommandProcessingStateEnum",
      "values": [
        "RECEIVED",
        "ACCEPTED",
        "REJECTED",
        "CANCELED"
      ],
      "cite": "SPC-001 §5.1.1 Fig 5.1-3, Table 5.1-2; RECEIVED may not be reported; ACCEPTED/REJECTED/CANCELED terminal"
    },
    "MessageModeEnum": {
      "name": "MessageModeEnum",
      "values": [
        "LIVE",
        "EXERCISE",
        "SIMULATION",
        "NONEXERCISE_SIMULATION"
      ],
      "cite": "XSD MessageModeEnum"
    },
    "CannotComplyEnum": {
      "name": "CannotComplyEnum",
      "values": [
        "INVALID_INPUT_PARAMETER"
      ],
      "cite": "XSD CannotComplyEnum; CannotComplyType.Reason on CommandStatusBaseType (SPC-001 §5.1.1)"
    },
    "RequestProcessingStateEnum": {
      "name": "RequestProcessingStateEnum",
      "values": [
        "QUEUED",
        "PROCESSING",
        "COMPLETED",
        "FAILED",
        "CANCELED",
        "REJECTED"
      ],
      "cite": "SPC-001 §5.1.2/§5.1.3 (RequestStatus); XSD RequestProcessingStateEnum"
    }
  },
  "envelope": {
    "MessageType": {
      "name": "MessageType",
      "cite": "XSD MessageType — abstract envelope",
      "fields": [
        {
          "name": "SecurityInformation",
          "required": true,
          "cite": "read-only marking chip; type in UCI_SecurityMarkings (not vendored)"
        },
        {
          "name": "MessageHeader",
          "required": true,
          "ref": "HeaderType"
        }
      ]
    },
    "HeaderType": {
      "name": "HeaderType",
      "cite": "XSD HeaderType",
      "fields": [
        {
          "name": "SystemID",
          "required": true,
          "cite": "player-filled (beat 1); missing SystemID => ENV HeaderType finding"
        },
        {
          "name": "Timestamp",
          "required": true,
          "cite": "XSD HeaderType (DateTimeType)"
        },
        {
          "name": "SchemaVersion",
          "required": true,
          "cite": "XSD HeaderType (UCI_SchemaVersionStringType)"
        },
        {
          "name": "Mode",
          "required": false,
          "enum": "MessageModeEnum"
        },
        {
          "name": "ServiceID",
          "required": false,
          "cite": "optional; omitted from the 4-field inspector"
        },
        {
          "name": "MissionID",
          "required": false,
          "cite": "optional; omitted from the 4-field inspector"
        }
      ]
    }
  },
  "messages": {
    "TaskCommand": {
      "name": "TaskCommand",
      "cite": "UNIS §4.6 CERT UNIS-000105; SPC-001 §5.1.1 CERT SCH-002461; XSD TaskCommand / TaskCommandMT",
      "fields": [
        {
          "name": "CommandID",
          "required": true,
          "ref": "ID_Type",
          "cite": "ID_Type.UUID; RQMT USTD-000436 (Leach-Salz/nil), RQMT USTD-000673 (canonical string)"
        },
        {
          "name": "CommandState",
          "required": true,
          "enum": "CommandStateEnum"
        }
      ],
      "mt": "TaskCommandMT",
      "role": "request"
    },
    "TaskCommandStatus": {
      "name": "TaskCommandStatus",
      "cite": "UNIS §4.6 CERT UNIS-000105; SPC-001 §5.1.1 CERT SCH-002461; XSD TaskCommandStatus / TaskCommandStatusMT",
      "fields": [
        {
          "name": "CommandID",
          "required": true,
          "ref": "ID_Type",
          "cite": "correlation key back to the TaskCommand"
        },
        {
          "name": "CommandProcessingState",
          "required": true,
          "enum": "CommandProcessingStateEnum"
        },
        {
          "name": "CommandProcessingStateReason",
          "required": false,
          "cite": "CannotComplyType.Reason (CannotComplyEnum); populated on REJECTED — sheet 1-3"
        }
      ],
      "mt": "TaskCommandStatusMT",
      "role": "response"
    },
    "SubsystemStatus": {
      "name": "SubsystemStatus",
      "cite": "UNIS §4.1 CERT UNIS-000076; structure SPC-001 §5.1.6; XSD SubsystemStatus / SubsystemStatusMT",
      "fields": [],
      "mt": "SubsystemStatusMT",
      "role": "publication"
    },
    "Entity": {
      "name": "Entity",
      "cite": "UNIS §4.2 CERT UNIS-000081; structure SPC-001 §5.1.5; XSD Entity / EntityMT",
      "fields": [],
      "mt": "EntityMT",
      "role": "publication"
    },
    "SubsystemStatusDataRequest": {
      "name": "SubsystemStatusDataRequest",
      "cite": "UNIS §4.4 CERT UNIS-000093; structure SPC-001 §5.1.3 CERT SCH-002462; XSD SubsystemStatusDataRequest / SubsystemStatusDataRequestMT",
      "fields": [],
      "mt": "SubsystemStatusDataRequestMT",
      "role": "request"
    },
    "SubsystemStatusDataRequestStatus": {
      "name": "SubsystemStatusDataRequestStatus",
      "cite": "UNIS §4.4 CERT UNIS-000093; structure SPC-001 §5.1.3 CERT SCH-002462; XSD SubsystemStatusDataRequestStatus / SubsystemStatusDataRequestStatusMT",
      "fields": [
        {
          "name": "RequestProcessingState",
          "required": true,
          "enum": "RequestProcessingStateEnum"
        }
      ],
      "mt": "SubsystemStatusDataRequestStatusMT",
      "role": "response"
    },
    "AnalysisRouteRequest": {
      "name": "AnalysisRouteRequest",
      "cite": "UNIS §4.5 CERT UNIS-000099; structure SPC-001 §5.1.2 CERT SCH-002463; XSD AnalysisRouteRequest / AnalysisRouteRequestMT",
      "fields": [],
      "mt": "AnalysisRouteRequestMT",
      "role": "request"
    },
    "AnalysisRouteRequestStatus": {
      "name": "AnalysisRouteRequestStatus",
      "cite": "UNIS §4.5 CERT UNIS-000099; structure SPC-001 §5.1.2 CERT SCH-002463; XSD AnalysisRouteRequestStatus / AnalysisRouteRequestStatusMT",
      "fields": [
        {
          "name": "RequestProcessingState",
          "required": true,
          "enum": "RequestProcessingStateEnum"
        }
      ],
      "mt": "AnalysisRouteRequestStatusMT",
      "role": "response"
    }
  },
  "types": {
    "ID_Type": {
      "name": "ID_Type",
      "cite": "XSD ID_Type = UUID + optional DescriptiveLabel",
      "fields": [
        {
          "name": "UUID",
          "required": true
        },
        {
          "name": "DescriptiveLabel",
          "required": false
        }
      ]
    }
  }
} as const;

export type MessageCatalog = typeof MESSAGE_CATALOG;

/* --- Validator findings (battery V1–V10; quotes policed verbatim) --- */
export const FINDINGS = {
  "V1-systemid": {
    "id": "V1-systemid",
    "code": "ENV HeaderType",
    "message": "MessageHeader missing required SystemID",
    "source": "xsd",
    "docRef": "XSD HeaderType",
    "quote": "This element represents the SystemID of the System that sent this message."
  },
  "V2-timestamp": {
    "id": "V2-timestamp",
    "code": "ENV HeaderType",
    "message": "Timestamp missing or not ISO-8601",
    "source": "xsd",
    "docRef": "XSD HeaderType (DateTimeType)",
    "quote": "This element represents the time and date at which the message was created and ready to be sent."
  },
  "V3-schemaversion": {
    "id": "V3-schemaversion",
    "code": "ENV HeaderType",
    "message": "SchemaVersion missing or malformed",
    "source": "xsd",
    "docRef": "XSD HeaderType / UCI_SchemaVersionStringType",
    "quote": "Indicates the schema version used to generate the message."
  },
  "V4-mode-enum": {
    "id": "V4-mode-enum",
    "code": "ENV HeaderType",
    "message": "Mode is not a valid MessageModeEnum value",
    "source": "xsd",
    "docRef": "XSD HeaderType / MessageModeEnum",
    "quote": "See enumeration values for details."
  },
  "V4-mode-mismatch": {
    "id": "V4-mode-mismatch",
    "code": "ENV HeaderType",
    "message": "Mode does not match the sheet's declared mode",
    "source": "game-rule",
    "docRef": "game rule (mode-match, docs/02 lie #3)"
  },
  "V5-uuid-invalid": {
    "id": "V5-uuid-invalid",
    "code": "RQMT USTD-000436",
    "message": "CommandID is not a valid RFC-4122 UUID",
    "source": "std",
    "docRef": "STD-001 §3",
    "quote": "UCI UUIDs shall conform to any version of the Leach-Salz UUID variant (variant 1) or the nil UUID described in RFC 4122."
  },
  "V6-uuid-noncanonical": {
    "id": "V6-uuid-noncanonical",
    "code": "RQMT USTD-000673",
    "message": "CommandID is not in canonical UUID string form",
    "source": "std",
    "docRef": "STD-001 §3",
    "quote": "UCI UUIDs shall conform to the UUID string representation"
  },
  "V7-commandstate": {
    "id": "V7-commandstate",
    "code": "ENV CommandBaseType",
    "message": "CommandState is not a valid CommandStateEnum value",
    "source": "xsd",
    "docRef": "XSD CommandBaseType",
    "quote": "The state of the command message data."
  },
  "V8-binding": {
    "id": "V8-binding",
    "code": "CERT SCH-002461",
    "message": "request/response must be named <MsgName>Command / <MsgName>CommandStatus",
    "source": "spc",
    "docRef": "SPC-001 §5.1.1",
    "quote": "All Command-2 primitive types shall consist of two messages with names of the form"
  },
  "V9-roles": {
    "id": "V9-roles",
    "code": "CERT UNIS-000105",
    "message": "both Command-2 roles must be bound to lifelines",
    "source": "unis",
    "docRef": "UNIS §4.6",
    "quote": "A UCI Component fulfilling a role identified in the Command-2 message interaction pattern shall follow the interaction pattern"
  },
  "V10-terminal-handler": {
    "id": "V10-terminal-handler",
    "code": "READY",
    "message": "no handler wired for a reachable terminal state",
    "source": "game-rule",
    "docRef": "game rule (READY gate)"
  },
  "RUN-ordering": {
    "id": "RUN-ordering",
    "code": "UNIS §4",
    "message": "the bus assumes no ordering — gating ACCEPTED behind RECEIVED can hang",
    "source": "unis",
    "docRef": "UNIS §4 (Interaction Patterns)",
    "quote": "there can be no assumption that messages come in any order or that there is guaranteed delivery"
  },
  "RUN-terminal": {
    "id": "RUN-terminal",
    "code": "UNIS §4.6.2",
    "message": "acting on a response after a terminal state — the sequence had already ended",
    "source": "unis",
    "docRef": "UNIS §4.6.2 (Command-2 Terminal State Behavior)",
    "quote": "once a terminal state is reported, the sequence should end"
  },
  "RUN-stale": {
    "id": "RUN-stale",
    "code": "UNIS §4.2",
    "message": "a consumer went stale — a -1 datum owes no delivery; republish to keep it fresh",
    "source": "unis",
    "docRef": "UNIS §4 (no guaranteed delivery)",
    "quote": "there can be no assumption that messages come in any order or that there is guaranteed delivery"
  },
  "RUN-deadline": {
    "id": "RUN-deadline",
    "code": "UNIS §4.1",
    "message": "your status was not shown by the deadline — publish earlier, and again",
    "source": "unis",
    "docRef": "UNIS §4 (no guaranteed delivery)",
    "quote": "there can be no assumption that messages come in any order or that there is guaranteed delivery"
  },
  "JOB-wrong-palette": {
    "id": "JOB-wrong-palette",
    "code": "CERT UNIS-000093",
    "message": "a request needs a -2 pattern — no Status-1/Data-1 (-1) primitive can answer it",
    "source": "unis",
    "docRef": "SPC-002 §3 Table 3.0-1 / §4.4 (DataRequest-2)",
    "quote": "Consists of two messages where the first message requests data"
  }
} as const;

export type FindingId = keyof typeof FINDINGS;
export type FindingSpec = (typeof FINDINGS)[FindingId];

/* --- UCI Reference codex: curated prose layer (WS-D; names/CERTs/quotes policed) --- */
export const REFERENCE = {
  "overview": {
    "blurb": [
      "UCI — the Universal Command and Control (C2) Interface — is a messaging standard: a common grammar that lets independently built systems command, query, and inform each other without sharing code, hardware, or even a transport.",
      "Everything the game puts on the board is real: the message names, the fields, the state enums, and every rule that fails you is quoted verbatim from the standard. The game may omit; it never renames or invents."
    ],
    "quote": {
      "id": "overview",
      "source": "std",
      "cite": "STD-001 §1",
      "text": "Universal Command and Control (C2) Interface (UCI) is a messaging standard"
    },
    "documents": [
      {
        "key": "std",
        "title": "STD-001",
        "owns": "compliance requirements (RQMT USTD-…) — who must conform to what"
      },
      {
        "key": "unis",
        "title": "UNIS / SPC-002",
        "owns": "the interaction patterns and their CERT UNIS-… numbers — behavior on the wire"
      },
      {
        "key": "spc",
        "title": "SPC-001",
        "owns": "schema style and structure, the CERT SCH-… numbers — how a message is shaped"
      }
    ]
  },
  "patterns": [
    {
      "name": "Status-1",
      "roles": "Producer → Consumer(s)",
      "naming": "*Status (or a name matching no other primitive)",
      "unlocksAt": "0-1",
      "summary": "Fire-and-forget publication to one or more consumers; terminal on send, no acknowledgement. Announces state nobody has to accept.",
      "cite": "UNIS §4.1 CERT UNIS-000076; structure SPC-001 §5.1.6",
      "names": []
    },
    {
      "name": "Data-1",
      "roles": "Producer → Consumer(s)",
      "naming": "bare name (a datum, e.g. an Entity or a Plan)",
      "unlocksAt": "0-2",
      "summary": "Fire-and-forget publication of a datum other components reference; asynchronous and/or periodic. Like Status-1, no delivery is owed.",
      "cite": "UNIS §4.2 CERT UNIS-000081; structure SPC-001 §5.1.5",
      "names": []
    },
    {
      "name": "DataRecord-1",
      "roles": "Producer → Consumer(s)",
      "naming": "bare name; optional DataRecordInstanceID keys the record",
      "unlocksAt": "post-1.0 (World 2)",
      "summary": "Data-1 for managed records. With no instance ID it acts in the same manner as the Data-1 pattern; with one, the record has a lifecycle.",
      "cite": "UNIS §4.3 CERT UNIS-000087; structure SPC-001 §5.1.4 CERT SCH-002490",
      "names": [
        "DataRecordInstanceID"
      ]
    },
    {
      "name": "DataRequest-2",
      "roles": "Requester → Requestee",
      "naming": "*DataRequest / *DataRequestStatus",
      "unlocksAt": "1-4",
      "summary": "Ask for current data; the response is implicitly accepted by returning the requested status information. A request, not a command.",
      "cite": "UNIS §4.4 CERT UNIS-000093; structure SPC-001 §5.1.3 CERT SCH-002462",
      "names": []
    },
    {
      "name": "ActionRequest-2",
      "roles": "Requester → Requestee",
      "naming": "*Request / *RequestStatus",
      "unlocksAt": "1-4",
      "summary": "Ask a component to run a process that may be queued and worked over time; tracked through RequestProcessingStateEnum to a terminal state.",
      "cite": "UNIS §4.5 CERT UNIS-000099; structure SPC-001 §5.1.2 CERT SCH-002463",
      "names": []
    },
    {
      "name": "Command-2",
      "roles": "Commander → Commandee",
      "naming": "*Command / *CommandStatus",
      "unlocksAt": "1-1",
      "summary": "Demand an activity of a commandee and hold proof it happened; tracked through CommandProcessingStateEnum with a terminal state that ends the sequence.",
      "cite": "UNIS §4.6 CERT UNIS-000105; structure SPC-001 §5.1.1 CERT SCH-002461",
      "names": [
        "TaskCommand",
        "TaskCommandStatus"
      ]
    }
  ],
  "quotes": [
    {
      "id": "bus-no-ordering",
      "source": "unis",
      "cite": "UNIS §4",
      "text": "there can be no assumption that messages come in any order or that there is guaranteed delivery"
    },
    {
      "id": "terminal-end",
      "source": "unis",
      "cite": "UNIS §4.6.2",
      "text": "once a terminal state is reported, the sequence should end"
    },
    {
      "id": "received-optional",
      "source": "spc",
      "cite": "SPC-001 §5.1.1",
      "text": "that state may not be reported if the Commandee immediately transitions to one of the terminal states"
    },
    {
      "id": "terminal-ignore-cancel",
      "source": "xsd",
      "cite": "XSD CommandProcessingStateEnum (ACCEPTED / REJECTED annotations)",
      "text": "This is a terminal state and the Subsystem or Service will ignore all subsequent updates to the Command, including CANCEL."
    }
  ],
  "bridge": [
    {
      "primitive": "Command-2",
      "brainSwap": "MA_FlightCommandMT / MA_FlightCommandStatusMT",
      "serviceBus": "MA_TaskCommandMT / MA_TaskStatusMT round trip"
    },
    {
      "primitive": "ActionRequest-2",
      "brainSwap": "MA_ControlRequestMT / MA_ControlRequestStatusMT (the handshake)",
      "serviceBus": "MA_ApprovalRequestMT / MA_ApprovalRequestStatusMT (the QB approval gate)"
    },
    {
      "primitive": "DataRequest-2",
      "brainSwap": "SubsystemStatusDataRequestMT (on-demand status)",
      "serviceBus": "same demand class inside status interactions"
    },
    {
      "primitive": "Status-1",
      "brainSwap": "ControlStatusMT; SubsystemStatusMT / ServiceStatusMT heartbeats; TaskStatusMT",
      "serviceBus": "heartbeats and link-health reports (MA_CommTeamReportMT)"
    },
    {
      "primitive": "Data-1",
      "brainSwap": "MA_FlightCapabilityMT; MA_TaskMT; EntityMT tracks; MA_RoutePlanMT",
      "serviceBus": "COP distribution / sensor-track fan-out"
    },
    {
      "primitive": "DataRecord-1",
      "brainSwap": "MA_FaultMT; FileMetadataMT",
      "serviceBus": "Mission Data Package artifacts (MP class pre-load)"
    }
  ]
} as const;

export type Reference = typeof REFERENCE;
